sudo: required

dist: xenial

services:
  - docker

language: node_js

node_js:
  - 11
  - 10

before_install:
  - apt-get install -yqq strace
  # https://unix.stackexchange.com/questions/156103/why-strace-ignores-my-alias-for-rm/156108
  - alias my_strace="strace -ff -e trace=/traces/strace_log "

script:
  # - docker pull sysdig/sysdig:0.26.4
  # - docker run -v /var/run/docker.sock:/host/var/run/docker.sock -v /dev:/host/dev -v /proc:/host/proc:ro -v /boot:/host/boot:ro -v /lib/modules:/host/lib/modules:ro -v /usr:/host/usr:ro -v /traces:/traces --name sysdig sysdig/sysdig:0.26.4 bash -c "sysdig -z -C 2048 -qw /traces/npmjs.$(date +'%Y%m%d-%H%M%S').scap.gz container.image != sysdig/sysdig"
  # - sleep 10
  - my_strace npm install express
  - my_strace npm install eslint

