sudo: required

dist: xenial

services:
  - docker

language: node_js

node_js:
  - 11

before_install:
  - sudo apt-get install -yqq strace curl
  - sudo mkdir /traces/
  - sudo chmod a+w /traces/
  # https://unix.stackexchange.com/questions/156103/why-strace-ignores-my-alias-for-rm/156108
  # - alias my_strace="strace -ff -e trace=/traces/strace_log "

script:
  # - docker pull sysdig/sysdig:0.26.4
  # - docker run -v /var/run/docker.sock:/host/var/run/docker.sock -v /dev:/host/dev -v /proc:/host/proc:ro -v /boot:/host/boot:ro -v /lib/modules:/host/lib/modules:ro -v /usr:/host/usr:ro -v /traces:/traces --name sysdig sysdig/sysdig:0.26.4 bash -c "sysdig -z -C 2048 -qw /traces/npmjs.$(date +'%Y%m%d-%H%M%S').scap.gz container.image != sysdig/sysdig"
  # - sleep 10
  - strace -ff -o /traces/strace_log.express npm install express
  - strace -ff -o /traces/strace_log.eslint npm install eslint
  - ls -lht /traces/strace_log.express
  - ls -lht /traces/strace_log.eslint
  - curl --upload-file /traces/strace_log.express https://transfer.sh
  - curl --upload-file /traces/strace_log.eslint https://transfer.sh

